config: '/home/alberto/PycharmProjects/dts/config/'
data: '/home/alberto/PycharmProjects/dts/data/'
weights: '/home/alberto/PycharmProjects/dts/weights/'
imgs: '/home/alberto/PycharmProjects/dts/imgs/'
logs: '/home/alberto/PycharmProjects/dts/logs/'
ckpts: '/home/alberto/PycharmProjects/dts/ckpts/'
db: 'DTS'
