train: False
dataset: 'gefcom'
exogenous: True
epochs: 1
batch_size: 1024
input_sequence_length: 96
output_sequence_length:  24
dropout: 0.0
layers: 1
units: 30
learning_rate: 0.001
cell: 'gru'
l2: 0.001
MIMO: False
detrend: True