train: [False]
dataset: ['uci']
exogenous: [False]
epochs: [2]
batch_size: [1024]
input_sequence_length: [384]
output_sequence_length:  [96]
dropout: [0.0]
layers: [1]
units: [30]
learning_rate: [0.001]
cell: ['rnn']
l2: [0.001]
MIMO: [True]
load: [False]
detrend: [True]