train: [False]
dataset: ['uci']
exogenous: [False]
epochs: [1]
batch_size: [1024]
input_sequence_length: [384]
output_sequence_length:  [96]
dropout: [0.0]
units: [[30]]
learning_rate: [0.001]
cell: ['gru']
l2: [0.001]
teacher_forcing: [False]
load: [False]
detrend: [True]