train: [False]
dataset: ['gefcom']
exogenous: [True, False]
epochs: [200]
batch_size: [1024]
input_sequence_length: [96]
output_sequence_length:  [24]
dropout: [0.0]
units: [[10,10]]
learning_rate: [0.001]
cell: ['gru']
l2: [0.001]
teacher_forcing: [True, False]
detrend: [True, False]