epochs: [200]
batch_size: [1024]
input_sequence_length: [96]
output_sequence_length: [24]
dropout: [0.2]
layers: [6]
out_channels: [32]
kernel_size: [2]
dilation: [2]
l2_reg: [0.005]
learning_rate: [0.001]
preprocessing: [True]
exogenous: [True, False]
dataset: ['gefcom']
tcn_type: ['conditional_tcn']
train: [False]
detrend: [True,False]
# load: ['/home/alberto/PycharmProjects/dts/weights/conditional_tcn_uci_1564507825.7593954']