epochs: [200]
batch_size: [1024]
input_sequence_length: [384]
output_sequence_length: [96]
dropout: [0.2]
layers: [6]
out_channels: [32]
kernel_size: [2]
dilation: [2]
l2_reg: [0.005]
learning_rate: [0.001]
preprocessing: [True]
exogenous: [False]
dataset: ['uci']
tcn_type: ['conditional_tcn']
train: [False]
detrend: [True, False]