epochs: [1]
batch_size: [1024]
input_sequence_length: [96]
output_sequence_length: [24]
dropout: [0.2]
layers: [3]
out_channels: [2]
kernel_size: [2]
dilation: [2]
l2_reg: [0.005]
learning_rate: [0.001]
preprocessing: [True]
exogenous: [False, True]
dataset: ['gefcom']
tcn_type: ['conditional_tcn', 'wavenet', 'tcn']
train: [False]
detrend: [True, False]